services:
  db:
    image: pgvector/pgvector:16
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=appuser
      - POSTGRES_DB=main

volumes:
  db:
