services:
  db:
    image: pgvector/pgvector:16
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=main
      - TZ=UTC
    mem_limit: 8g
    cpu_count: 2

volumes:
  db:
