services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - docker.postgres.env
    mem_limit: 8g
    cpu_count: 2
    networks:
      - default

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    env_file:
      - docker.n8n.env
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - default

  # datadog-agent:
  #   image: datadog/agent:latest
  #   env_file:
  #   - docker.datadog-agent.env
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock:ro
  #   - /proc/:/host/proc/:ro
  #   - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  #   ports:
  #   - 127.0.0.1:8126:8126/tcp
  #   environment:
  #   - DD_APM_ENABLED=true
  #   - DD_APM_NON_LOCAL_TRAFFIC=true
  #   - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
  #   - DD_AC_EXCLUDE=name:datadog-agent
  #   - DD_HOSTNAME=profiler-example

volumes:
  postgres-data:
  n8n-data:

networks:
  default:
