on:
  push:
    branches: [develop, staging, main]

jobs:
  dev:
    name: deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: development
      ref: ${{ github.sha }}
    secrets: inherit
  staging:
    if: ${{ github.ref == 'refs/heads/staging' || github.base_ref == 'staging' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
    with:
      environment: staging
      ref: ${{ github.sha }}
    secrets: inherit
  prod:
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/_deployment.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: production
      ref: ${{ github.sha }}
    secrets: inherit
